function pitchedTone (tone: number) {
    return tone + pitchModifier * pitchMultiplier
}
input.onButtonPressed(Button.B, function () {
    basic.showLeds(`
        . # # # #
        . # # # #
        . # . . #
        # # . # #
        # # . # #
        `)
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(370), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(392), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(659), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(659), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(659), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(370), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(392), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(659), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(659), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(659), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(370), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(392), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(659), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(659), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(659), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(370), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(392), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(659), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(659), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(659), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(370), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(392), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(659), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(659), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(659), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(370), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(392), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(494), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(659), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Whole))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(440), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(587), music.beat(BeatFraction.Quarter))
    music.playTone(pitchedTone(659), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(659), music.beat(BeatFraction.Half))
    music.playTone(pitchedTone(554), music.beat(BeatFraction.Whole))
})
let pitchModifier = 0
let pitchMultiplier = 0
pitchMultiplier = 40
basic.showLeds(`
    . . # . .
    . . # # .
    . . # . #
    # # # . .
    # # # . .
    `)
basic.showIcon(IconNames.EigthNote)
// music.playTone(pitchModifier, music.beat(BeatFraction.Whole))
basic.forever(function () {
    music.setTempo(pins.map(
    Math.abs(input.acceleration(Dimension.X)),
    0,
    1023,
    60,
    320
    ))
    // * 18
    pitchModifier = pins.map(
    input.lightLevel(),
    0,
    255,
    -1,
    15
    )
})
